### ISSUE TITLE
Server url

### ISSUE THREAD

**Issue by akatsukle** [anttiviljami/openapi-backend#15]
Consider the following spec:
```YAML
openapi: "3.0.0"
servers:
  - url: http://localhost:8080/openapi
paths:
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: OK
 ```

In the current state, running a query on 
- `http://localhost:8080/test` will return a 200 where a 404 was expected
- `http://localhost:8080/openapi/test` will return a 404 instead of a 200.

This behaviour sounds wrong to me, but for a few reasons, I'm not sure whether openapi-backend should handle it or not, because in the event where more than one server is specified, without using the hostname, there can be ambiguous routes.
For instance, consider the following case:
```YAML
openapi: "3.0.0"
servers:
  - url: http://domain2:8080/
  - url: http://domain1:8080/test
paths:
  /:
    get:
      operationId: test
      responses:
        '200':
          description: OK
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: OK2
 ```

I believe either the following can be done:
- Add a note in the docs, saying this is unsupported, leaving the responsibility of rewriting the path to the application.
- Read the `host` header and use this to compute the appropriate path before matching. I'm not sure if this is going to work on every case, but it should I guess. If going down that road, I guess taking a parameter to enable/disable this behavior would also be a good idea.

I would love to hear your opinion about that.

**Comment by anttiviljami** [comment]
I think I disagree with you here about this being wrong behaviour, but you have a good point here. OpenAPIBackend should always be handling routes relative to your api root. This should be documented.

Say you want your api to run under http://localhost:8080/api, here's what you would do in express:

```javascript
app.use('/api', api.handleRequest({
  method: req.method,
  path: req.path.replace(/^\/api/, ''), // strip the api root path
  query: req.query,
  body: req.body,
  headers: req.headers,
}, req, res)
```

Perhaps we should add a constructor option, so you don't need to manually strip the api root (default: '/') ? Would this help solve your problem?

OpenAPIBackend shouldn't look at the OpenAPI servers property in your definition for this information, because we don't know how your app is configured. For example when running in Serverless framework (AWS Lambda), the api root is always relative to `/{stage}`, but api gateway automatically strips the api root from the passed request path.

**Comment by anttiviljami** [comment]
I'd say let's add a constructor opt called `apiRoot` which will be used to make paths root-relative by stripping the passed root path from requests.

**Comment by mt-richard-garnier** [comment]
Nice ! Thanks

**Comment by akatsukle** [comment]
Nice ! Thanks
