### ISSUE TITLE
oneOf, anyOf, allOf, not implemented?

### ISSUE THREAD

**Issue by kaasdude** [anttiviljami/openapi-backend#42]
Hello,

I'm trying to use the OpenAPI feature to have a request body which is able to receive 2 or more types of body object structures, e.g:

(As mentioned here: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#oneof)

**Paths:**
```yaml
paths:
  '/pets':
    get:
      summary: List pets
      description: Find a list of pets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

    post:
      summary: Spawn animal
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: OK
```

**With corresponding components:**

```yaml
components:
  schemas:

    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 4

    Dog:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 4
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]

    Cat:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 4
        hunts:
          type: boolean
        age:
          type: integer
```

I try to send this object:

```JSON
{"id":423,"bark":true,"breed":"Dingo"}

```

Because currently I'm getting this error:
HTTP status: 400

```
{
  "err": [
    {
      "keyword": "oneOf",
      "dataPath": ".requestBody",
      "schemaPath": "#/properties/requestBody/oneOf",
      "params": {
        "passingSchemas": [
          0,
          1
        ]
      },
      "message": "should match exactly one schema in oneOf"
    }
  ]
}
```

**Comment by anttiviljami** [comment]
Hi @kaasdude !

Looks like the error message is correct. If you have a look at it, it says that both your schemas are passing and it's expecting only one to pass.

This is because by default in JSON schema, `additionalProperties` is set to `true`. You need to explicitly state `additionalProperties: false` for both your object schemas to correctly validate this. Alternatively, you can use `anyOf` instead of `oneOf`.

See https://json-schema.org/understanding-json-schema/reference/object.html

**Comment by kaasdude** [comment]
Thanks! Silly me. Works like a charm!

**Comment by rehanvdm** [comment]
Just want to add an extra piece of info here, if someone also experiences it. I had multiple responses. Thinking that it would match the 200 responses, but it matched 2 responses. I had to make each of the 400, 403, 500 error properties required so that when it matches the data, it picks the 200 response type. 

![image](https://user-images.githubusercontent.com/22810856/142603180-5109b8f8-ca99-4679-959c-70bed09a4594.png)
